/*
* Copyright 2014
* Jason LuBean <jason.lubean@gmail.com>
* https://github.com/jlubean/iso-639-2
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
* MA 02110-1301, USA.
*/

(function(exports) {

    var alpha2Map, alpha3Map,

    labels = {
        a3: "ISO 639-2 Bibliographic Language Code",
        a3t: "ISO 639-2 Terminology Language Code",
        a2: "ISO 639-1 Language Code",
        name: "Native Name",
        eng: "English Name",
        dir: "Reading Direction"
    },

    data = [
        ["aar","","aa","ʿAfár af","Afar","ltr"],
        ["abk","","ab","Аҧсуа","Abkhazian","ltr"],
        ["ace","","","Achinese","Achinese","ltr"],
        ["ach","","","Acoli","Acoli","ltr"],
        ["ada","","","Adangbɛ","Adangme","ltr"],
        ["ady","","","Aдыгэбзэ","Adyghe; Adygei","ltr"],
        ["afa","","","Afro-Asiatic languages","Afro-Asiatic languages","ltr"],
        ["afh","","","Afrihili","Afrihili","ltr"],
        ["afr","","af","Afrikaans","Afrikaans","ltr"],
        ["ain","","","アイヌ イタク","Ainu","ltr"],
        ["aka","","ak","Akana","Akan","ltr"],
        ["akk","","","Akkadian","Akkadian","ltr"],
        ["alb","sqi","sq","Shqip","Albanian","ltr"],
        ["ale","","","Unangam Tunuu","Aleut","ltr"],
        ["alg","","","Algonquian languages","Algonquian languages","ltr"],
        ["alt","","","Southern Altai","Southern Altai","ltr"],
        ["amh","","am","አማርኛ","Amharic","ltr"],
        ["ang","","","English, Old (ca.450-1100)","English, Old (ca.450-1100)","ltr"],
        ["anp","","","Angika","Angika","ltr"],
        ["apa","","","Ndéé","Apache","ltr"],
        ["ara","","ar","العربية","Arabic","rtl"],
        ["arc","","","Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)","Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)","ltr"],
        ["arg","","an","Aragonés","Aragonese","ltr"],
        ["arm","hye","hy","Հայերեն","Armenian","ltr"],
        ["arn","","","Mapudungun; Mapuche","Mapudungun; Mapuche","ltr"],
        ["arp","","","Hinono'eitiitt","Arapaho","ltr"],
        ["art","","","Artificial languages","Artificial languages","ltr"],
        ["arw","","","Arawak","Arawak","ltr"],
        ["asm","","as","অসমীয়া","Assamese","ltr"],
        ["ast","","","Llïonés","Asturian; Bable; Leonese; Asturleonese","ltr"],
        ["ath","","","Athapascan languages","Athapascan languages","ltr"],
        ["aus","","","Australian languages","Australian languages","ltr"],
        ["ava","","av","Авар","Avaric","ltr"],
        ["ave","","ae","Avestan","Avestan","ltr"],
        ["awa","","","Awadhi","Awadhi","ltr"],
        ["aym","","ay","Aymar Aru","Aymara","ltr"],
        ["aze","","az","Azərbaycanca / آذربايجان","Azerbaijani","ltr"],
        ["bad","","","Banda languages","Banda languages","ltr"],
        ["bai","","","Bamileke languages","Bamileke languages","ltr"],
        ["bak","","ba","Башҡорт","Bashkir","ltr"],
        ["bal","","","Baluchi","Baluchi","ltr"],
        ["bam","","bm","Bamanankan","Bambara","ltr"],
        ["ban","","","Balinese","Balinese","ltr"],
        ["baq","eus","eu","Euskara","Basque","ltr"],
        ["bas","","","Basa","Basa","ltr"],
        ["bat","","","Baltic languages","Baltic languages","ltr"],
        ["bej","","","Beja; Bedawiyet","Beja; Bedawiyet","ltr"],
        ["bel","","be","Беларуская","Belarusian","ltr"],
        ["bem","","","iciBemba","Bemba","ltr"],
        ["ben","","bn","বাংলা","Bengali","ltr"],
        ["ber","","","Tamaziɣt","Berber","ltr"],
        ["bho","","","भोजपुरी, بھوجپوري","Bhojpuri","ltr"],
        ["bih","","bh","भोजपुरी","Bihari","ltr"],
        ["bik","","","Bikol","Bikol","ltr"],
        ["bin","","","Bini; Edo","Bini; Edo","ltr"],
        ["bis","","bi","Bislama","Bislama","ltr"],
        ["bla","","","Siksika","Siksika","ltr"],
        ["bnt","","","Bantu languages","Bantu languages","ltr"],
        ["bos","","bs","Босански / Bosanski","Bosnian","ltr"],
        ["bra","","","Braj","Braj","ltr"],
        ["bre","","br","Brezhoneg","Breton","ltr"],
        ["btk","","","Batak languages","Batak languages","ltr"],
        ["bua","","","Buriat","Buriat","ltr"],
        ["bug","","","Buginese","Buginese","ltr"],
        ["bul","","bg","Български","Bulgarian","ltr"],
        ["bur","mya","my","မြန်မာစာ / မြန်မာစကား","Burmese","ltr"],
        ["byn","","","Blin; Bilin","Blin; Bilin","ltr"],
        ["cad","","","Caddo","Caddo","ltr"],
        ["cai","","","Central American Indian languages","Central American Indian languages","ltr"],
        ["car","","","Galibi Carib","Galibi Carib","ltr"],
        ["cat","","ca","Català","Catalan; Valencian","ltr"],
        ["cau","","","Caucasian languages","Caucasian languages","ltr"],
        ["ceb","","","Bisaya / Sinugbuanon","Cebuano","ltr"],
        ["cel","","","Celtic languages","Celtic languages","ltr"],
        ["cha","","ch","Chamoru","Chamorro","ltr"],
        ["chb","","","Chibcha","Chibcha","ltr"],
        ["che","","ce","Нохчийн","Chechen","ltr"],
        ["chg","","","Chagatai","Chagatai","ltr"],
        ["chi","zho","zh","中文","Chinese","ltr"],
        ["chk","","","Chuukese","Chuukese","ltr"],
        ["chm","","","Mari","Mari","ltr"],
        ["chn","","","Chinook jargon","Chinook jargon","ltr"],
        ["cho","","","Chahta'","Choctaw","ltr"],
        ["chp","","","ᑌᓀᓲᒢᕄᓀ / Dene Suline / Dëne Sųłiné","Chipewyan; Dene Suline","ltr"],
        ["chr","","","Cherokee","Cherokee","ltr"],
        ["chu","","cu","словѣньскъ / slověnĭskŭ","Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic","ltr"],
        ["chv","","cv","Чăваш","Chuvash","ltr"],
        ["chy","","","Cheyenne","Cheyenne","ltr"],
        ["cmc","","","Chamic languages","Chamic languages","ltr"],
        ["cop","","","Coptic","Coptic","ltr"],
        ["cor","","kw","Kernewek","Cornish","ltr"],
        ["cos","","co","Corsu","Corsican","ltr"],
        ["cpe","","","Creoles and pidgins, English based","Creoles and pidgins, English based","ltr"],
        ["cpf","","","Creoles and pidgins, French-based","Creoles and pidgins, French-based","ltr"],
        ["cpp","","","Creoles and pidgins, Portuguese-based","Creoles and pidgins, Portuguese-based","ltr"],
        ["cre","","cr","ᓀᐦᐃᔭᐍᐏᐣ","Cree","ltr"],
        ["crh","","","Crimean Tatar; Crimean Turkish","Crimean Tatar; Crimean Turkish","ltr"],
        ["crp","","","Creoles and pidgins","Creoles and pidgins","ltr"],
        ["csb","","","Kashubian","Kashubian","ltr"],
        ["cus","","","Cushitic languages","Cushitic languages","ltr"],
        ["cze","ces","cs","Český","Czech","ltr"],
        ["dak","","","Dakȟótiyapi","Dakota","ltr"],
        ["dan","","da","Dansk","Danish","ltr"],
        ["dar","","","Дарган Mез","Dargwa","ltr"],
        ["day","","","Land Dayak languages","Land Dayak languages","ltr"],
        ["del","","","Delaware","Delaware","ltr"],
        ["den","","","Slave (Athapascan)","Slave (Athapascan)","ltr"],
        ["dgr","","","Dogrib","Dogrib","ltr"],
        ["din","","","Dinka","Dinka","ltr"],
        ["div","","dv","Divehi; Dhivehi; Maldivian","Divehi; Dhivehi; Maldivian","rtl"],
        ["doi","","","Dogri","Dogri","ltr"],
        ["dra","","","Dravidian languages","Dravidian languages","ltr"],
        ["dsb","","","Lower Sorbian","Lower Sorbian","ltr"],
        ["dua","","","Duala","Duala","ltr"],
        ["dum","","","Dutch, Middle (ca.1050-1350)","Dutch, Middle (ca.1050-1350)","ltr"],
        ["dut","nld","nl","Nederlands","Dutch; Flemish","ltr"],
        ["dyu","","","Dyula","Dyula","ltr"],
        ["dzo","","dz","ཇོང་ཁ","Dzongkha","ltr"],
        ["efi","","","Efik","Efik","ltr"],
        ["egy","","","Egyptian (Ancient)","Egyptian (Ancient)","ltr"],
        ["eka","","","Ekajuk","Ekajuk","ltr"],
        ["elx","","","Elamite","Elamite","ltr"],
        ["eng","","en","English","English","ltr"],
        ["enm","","","English, Middle (1100-1500)","English, Middle (1100-1500)","ltr"],
        ["epo","","eo","Esperanto","Esperanto","ltr"],
        ["est","","et","Eesti","Estonian","ltr"],
        ["ewe","","ee","Ɛʋɛ","Ewe","ltr"],
        ["ewo","","","Ewondo","Ewondo","ltr"],
        ["fan","","","Fang","Fang","ltr"],
        ["fao","","fo","Føroyskt","Faroese","ltr"],
        ["fat","","","Fanti","Fanti","ltr"],
        ["fij","","fj","Na Vosa Vakaviti","Fijian","ltr"],
        ["fil","","","Filipino; Pilipino","Filipino; Pilipino","ltr"],
        ["fin","","fi","Suomi","Finnish","ltr"],
        ["fiu","","","Finno-Ugrian languages","Finno-Ugrian languages","ltr"],
        ["fon","","","Fon","Fon","ltr"],
        ["fre","fra","fr","Français","French","ltr"],
        ["frm","","","French, Middle (ca.1400-1600)","French, Middle (ca.1400-1600)","ltr"],
        ["fro","","","French, Old (842-ca.1400)","French, Old (842-ca.1400)","ltr"],
        ["frr","","","Noordfreesk","Northern Frisian","ltr"],
        ["frs","","","Seeltersk","Eastern Frisian","ltr"],
        ["fry","","fy","Frysk","Western Frisian","ltr"],
        ["ful","","ff","Fulfulde","Fulah","ltr"],
        ["fur","","","Furlan","Friulian","ltr"],
        ["gaa","","","Gã","Ga","ltr"],
        ["gay","","","Gayo","Gayo","ltr"],
        ["gba","","","Gbaya","Gbaya","ltr"],
        ["gem","","","Germanic languages","Germanic languages","ltr"],
        ["geo","kat","ka","ქართული","Georgian","ltr"],
        ["ger","deu","de","Deutsch","German","ltr"],
        ["gez","","","Geez","Geez","ltr"],
        ["gil","","","Gilbertese","Gilbertese","ltr"],
        ["gla","","gd","Gàidhlig","Gaelic; Scottish Gaelic","ltr"],
        ["gle","","ga","Gaeilge","Irish","ltr"],
        ["glg","","gl","Galego","Galician","ltr"],
        ["glv","","gv","Gaelg","Manx","ltr"],
        ["gmh","","","German, Middle High (ca.1050-1500)","German, Middle High (ca.1050-1500)","ltr"],
        ["goh","","","German, Old High (ca.750-1050)","German, Old High (ca.750-1050)","ltr"],
        ["gon","","","Gondi","Gondi","ltr"],
        ["gor","","","Gorontalo","Gorontalo","ltr"],
        ["got","","","Gothic","Gothic","ltr"],
        ["grb","","","Grebo","Grebo","ltr"],
        ["grc","","","Greek, Ancient (to 1453)","Greek, Ancient (to 1453)","ltr"],
        ["gre","ell","el","Ελληνικά","Greek, Modern (1453-)","ltr"],
        ["grn","","gn","Avañe'ẽ","Guarani","ltr"],
        ["gsw","","","Schwyzerdütsch","Swiss German; Alemannic; Alsatian","ltr"],
        ["guj","","gu","ગુજરાતી","Gujarati","ltr"],
        ["gwi","","","Gwich'in","Gwich'in","ltr"],
        ["hai","","","Xaat Kíl","Haida","ltr"],
        ["hat","","ht","Krèyol ayisyen","Haitian; Haitian Creole","ltr"],
        ["hau","","ha","هَوُسَ","Hausa","rtl"],
        ["haw","","","ʻŌlelo Hawaiʻi","Hawaiian","ltr"],
        ["heb","","he","עברית","Hebrew","rtl"],
        ["her","","hz","Otsiherero","Herero","ltr"],
        ["hil","","","Hiligaynon","Hiligaynon","ltr"],
        ["him","","","पहाड़ी","Himachali languages; Western Pahari languages","ltr"],
        ["hin","","hi","हिन्दी","Hindi","ltr"],
        ["hit","","","Hittite","Hittite","ltr"],
        ["hmn","","","lol Hmongb, lus Hmoob, lug Moob","Hmong; Mong","ltr"],
        ["hmo","","ho","Hiri Motu","Hiri Motu","ltr"],
        ["hrv","","hr","Hrvatski","Croatian","ltr"],
        ["hsb","","","Upper Sorbian","Upper Sorbian","ltr"],
        ["hun","","hu","Magyar","Hungarian","ltr"],
        ["hup","","","Hupa","Hupa","ltr"],
        ["iba","","","Iban","Iban","ltr"],
        ["ibo","","ig","Igbo","Igbo","ltr"],
        ["ice","isl","is","Íslenska","Icelandic","ltr"],
        ["ido","","io","Ido","Ido","ltr"],
        ["iii","","ii","ꆈꌠ꒿ / 四川彝语","Sichuan Yi; Nuosu","ltr"],
        ["ijo","","","Ijo languages","Ijo languages","ltr"],
        ["iku","","iu","ᐃᓄᒃᑎᑐᑦ","Inuktitut","ltr"],
        ["ile","","ie","Interlingue","Interlingue; Occidental","ltr"],
        ["ilo","","","Iloko","Iloko","ltr"],
        ["ina","","ia","Interlingua","Interlingua (International Auxiliary Language Association)","ltr"],
        ["inc","","","Indic languages","Indic languages","ltr"],
        ["ind","","id","Bahasa Indonesia","Indonesian","ltr"],
        ["ine","","","Indo-European languages","Indo-European languages","ltr"],
        ["inh","","","ГӀалгӀай мотт","Ingush","ltr"],
        ["ipk","","ik","Iñupiak","Inupiaq","ltr"],
        ["ira","","","Iranian languages","Iranian languages","ltr"],
        ["iro","","","Iroquoian languages","Iroquoian languages","ltr"],
        ["ita","","it","Italiano","Italian","ltr"],
        ["jav","","jv","Basa Jawa","Javanese","ltr"],
        ["jbo","","","Lojban","Lojban","ltr"],
        ["jpn","","ja","日本語","Japanese","ltr"],
        ["jpr","","","Judeo-Persian","Judeo-Persian","ltr"],
        ["jrb","","","Judeo-Arabic","Judeo-Arabic","ltr"],
        ["kaa","","","Қарақалпақ","Kara-Kalpak","ltr"],
        ["kab","","","شئعم","Kabyle","ltr"],
        ["kac","","","Kachin; Jingpho","Kachin; Jingpho","ltr"],
        ["kal","","kl","Kalaallisut","Kalaallisut; Greenlandic","ltr"],
        ["kam","","","Kamba","Kamba","ltr"],
        ["kan","","kn","ಕನ್ನಡ","Kannada","ltr"],
        ["kar","","","Karen languages","Karen languages","ltr"],
        ["kas","","ks","कश्मीरी / كشميري","Kashmiri","rtl"],
        ["kau","","kr","Kanuri","Kanuri","ltr"],
        ["kaw","","","Kawi","Kawi","ltr"],
        ["kaz","","kk","Қазақ Tілі","Kazakh","ltr"],
        ["kbd","","","Kъэбэрдеибзэ","Kabardian","ltr"],
        ["kha","","","Khasi","Khasi","ltr"],
        ["khi","","","Khoisan languages","Khoisan languages","ltr"],
        ["khm","","km","ភាសាខ្មែរ","Central Khmer","ltr"],
        ["kho","","","Khotanese; Sakan","Khotanese; Sakan","ltr"],
        ["kik","","ki","Gĩkũyũ","Kikuyu; Gikuyu","ltr"],
        ["kin","","rw","Kinyarwandi","Kinyarwanda","ltr"],
        ["kir","","ky","Kırgızca / Кыргызча","Kirghiz; Kyrgyz","ltr"],
        ["kmb","","","Kimbundu","Kimbundu","ltr"],
        ["kok","","","कोंकणी / Konknni / കൊങ്കണി / ಕೊಂಕಣಿ","Konkani","ltr"],
        ["kom","","kv","Коми","Komi","ltr"],
        ["kon","","kg","KiKongo","Kongo","ltr"],
        ["kor","","ko","조선말 / 한국어","Korean","ltr"],
        ["kos","","","Kosraean","Kosraean","ltr"],
        ["kpe","","","Kpelle","Kpelle","ltr"],
        ["krc","","","Karachay-Balkar","Karachay-Balkar","ltr"],
        ["krl","","","Karelian","Karelian","ltr"],
        ["kro","","","Kru languages","Kru languages","ltr"],
        ["kru","","","Kurukh","Kurukh","ltr"],
        ["kua","","kj","Kuanyama","Kuanyama; Kwanyama","ltr"],
        ["kum","","","Къумукъ Tил","Kumyk","ltr"],
        ["kur","","ku","Kurdí, کوردی, or K’öрди","Kurdish","rtl"],
        ["kut","","","Kutenai","Kutenai","ltr"],
        ["lad","","","Ladino","Ladino","ltr"],
        ["lah","","","Lahnda","Lahnda","ltr"],
        ["lam","","","Lamba","Lamba","ltr"],
        ["lao","","lo","ລາວ / Pha xa lao","Lao","ltr"],
        ["lat","","la","Latina","Latin","ltr"],
        ["lav","","lv","Latviešu","Latvian","ltr"],
        ["lez","","","Lezghian","Lezghian","ltr"],
        ["lim","","li","Lèmburgs","Limburgan; Limburger; Limburgish","ltr"],
        ["lin","","ln","Lingála","Lingala","ltr"],
        ["lit","","lt","Lietuvių","Lithuanian","ltr"],
        ["lol","","","Mongo","Mongo","ltr"],
        ["loz","","","Lozi","Lozi","ltr"],
        ["ltz","","lb","Lëtzebuergesch","Luxembourgish; Letzeburgesch","ltr"],
        ["lua","","","Luba-Lulua","Luba-Lulua","ltr"],
        ["lub","","lu","Luba-Katanga","Luba-Katanga","ltr"],
        ["lug","","lg","Luganda","Ganda","ltr"],
        ["lui","","","Cham'teela","Luiseno","ltr"],
        ["lun","","","Lunda","Lunda","ltr"],
        ["luo","","","Kavirondo / Dholuo","Luo (Kenya and Tanzania)","ltr"],
        ["lus","","","Lushai","Lushai","ltr"],
        ["mac","mkd","mk","Македонски","Macedonian","ltr"],
        ["mad","","","Madurese","Madurese","ltr"],
        ["mag","","","मगही","Magahi","ltr"],
        ["mah","","mh","Kajin Majel / Ebon","Marshallese","ltr"],
        ["mai","","","मैथिली / মৈথিলী","Maithili","ltr"],
        ["mak","","","Makasar","Makasar","ltr"],
        ["mal","","ml","മലയാളം","Malayalam","ltr"],
        ["man","","","Mandingo","Mandingo","ltr"],
        ["mao","mri","mi","Māori","Maori","ltr"],
        ["map","","","Austronesian languages","Austronesian languages","ltr"],
        ["mar","","mr","मराठी","Marathi","ltr"],
        ["mas","","","Masai","Masai","ltr"],
        ["may","msa","ms","Bahasa Melayu","Malay","ltr"],
        ["mdf","","","Moksha","Moksha","ltr"],
        ["mdr","","","Mandar","Mandar","ltr"],
        ["men","","","Mende","Mende","ltr"],
        ["mga","","","Irish, Middle (900-1200)","Irish, Middle (900-1200)","ltr"],
        ["mic","","","Mi'kmaq; Micmac","Mi'kmaq; Micmac","ltr"],
        ["min","","","Minangkabau","Minangkabau","ltr"],
        ["mis","","","Uncoded languages","Uncoded languages","ltr"],
        ["mkh","","","Mon-Khmer languages","Mon-Khmer languages","ltr"],
        ["mlg","","mg","Malagasy","Malagasy","ltr"],
        ["mlt","","mt","Malti","Maltese","ltr"],
        ["mnc","","","ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ","Manchu","ltr"],
        ["mni","","","Manipuri","Manipuri","ltr"],
        ["mno","","","Manobo languages","Manobo languages","ltr"],
        ["moh","","","Mohawk","Mohawk","ltr"],
        ["mon","","mn","Монгол Хэл / ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ","Mongolian","ltr"],
        ["mos","","","Mossi","Mossi","ltr"],
        ["mul","","","Multiple languages","Multiple languages","ltr"],
        ["mun","","","Munda languages","Munda languages","ltr"],
        ["mus","","","Mvskoke / Mvskokē","Muscogee Creek","ltr"],
        ["mwl","","","Mirandese","Mirandese","ltr"],
        ["mwr","","","Marwari","Marwari","ltr"],
        ["myn","","","Mayan languages","Mayan languages","ltr"],
        ["myv","","","Erzya","Erzya","ltr"],
        ["nah","","","Nahuatl languages","Nahuatl languages","ltr"],
        ["nai","","","North American Indian languages","North American Indian languages","ltr"],
        ["nap","","","Neapolitan","Neapolitan","ltr"],
        ["nau","","na","Dorerin Naoero","Nauru","ltr"],
        ["nav","","nv","Diné bizaad","Navajo; Navaho","ltr"],
        ["nbl","","nr","isiNdebele","Ndebele, South; South Ndebele","ltr"],
        ["nde","","nd","Sindebele","Ndebele, North; North Ndebele","ltr"],
        ["ndo","","ng","Oshiwambo","Ndonga","ltr"],
        ["nds","","","Plattdüütsch","Low German; Low Saxon; German, Low; Saxon, Low","ltr"],
        ["nep","","ne","नेपाली","Nepali","ltr"],
        ["new","","","नेपाल भाषा","Nepal Bhasa; Newari","ltr"],
        ["nia","","","Nias","Nias","ltr"],
        ["nic","","","Niger-Kordofanian languages","Niger-Kordofanian languages","ltr"],
        ["niu","","","Niuean","Niuean","ltr"],
        ["nno","","nn","Norsk (nynorsk)","Norwegian Nynorsk; Nynorsk, Norwegian","ltr"],
        ["nob","","nb","Bokmål, Norwegian; Norwegian Bokmål","Bokmål, Norwegian; Norwegian Bokmål","ltr"],
        ["nog","","","Nogai","Nogai","ltr"],
        ["non","","","Norse, Old","Norse, Old","ltr"],
        ["nor","","no","Norsk (bokmål / riksmål)","Norwegian","ltr"],
        ["nqo","","","N'Ko","N'Ko","ltr"],
        ["nso","","","Pedi; Sepedi; Northern Sotho","Pedi; Sepedi; Northern Sotho","ltr"],
        ["nub","","","Nubian languages","Nubian languages","ltr"],
        ["nwc","","","Classical Newari; Old Newari; Classical Nepal Bhasa","Classical Newari; Old Newari; Classical Nepal Bhasa","ltr"],
        ["nya","","ny","Chi-Chewa","Chichewa; Chewa; Nyanja","ltr"],
        ["nym","","","Nyamwezi","Nyamwezi","ltr"],
        ["nyn","","","Nyankole","Nyankole","ltr"],
        ["nyo","","","Nyoro","Nyoro","ltr"],
        ["nzi","","","Nzima","Nzima","ltr"],
        ["oci","","oc","Occitan","Occitan (post 1500)","ltr"],
        ["oji","","oj","ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin","Ojibwa","ltr"],
        ["ori","","or","ଓଡ଼ିଆ","Oriya","ltr"],
        ["orm","","om","Oromoo","Oromo","ltr"],
        ["osa","","","Osage","Osage","ltr"],
        ["oss","","os","Иронау","Ossetian; Ossetic","ltr"],
        ["ota","","","Turkish, Ottoman (1500-1928)","Turkish, Ottoman (1500-1928)","ltr"],
        ["oto","","","Otomian languages","Otomian languages","ltr"],
        ["paa","","","Papuan languages","Papuan languages","ltr"],
        ["pag","","","Pangasinan","Pangasinan","ltr"],
        ["pal","","","Pahlavi","Pahlavi","ltr"],
        ["pam","","","Pampanga; Kapampangan","Pampanga; Kapampangan","ltr"],
        ["pan","","pa","ਪੰਜਾਬੀ / पंजाबी / پنجابي","Panjabi; Punjabi","ltr"],
        ["pap","","","Papiamento","Papiamento","ltr"],
        ["pau","","","Palauan","Palauan","ltr"],
        ["peo","","","Persian, Old (ca.600-400 B.C.)","Persian, Old (ca.600-400 B.C.)","ltr"],
        ["per","fas","fa","فارسی","Persian","rtl"],
        ["phi","","","Philippine languages","Philippine languages","ltr"],
        ["phn","","","Phoenician","Phoenician","ltr"],
        ["pli","","pi","Pāli / पाऴि","Pali","ltr"],
        ["pol","","pl","Polski","Polish","ltr"],
        ["pon","","","Pohnpeian","Pohnpeian","ltr"],
        ["por","","pt","Português","Portuguese","ltr"],
        ["pra","","","Prakrit languages","Prakrit languages","ltr"],
        ["pro","","","Provençal, Old (to 1500);Occitan, Old (to 1500)","Provençal, Old (to 1500);Occitan, Old (to 1500)","ltr"],
        ["pus","","ps","پښتو","Pushto; Pashto","rtl"],
        ["qaa-qtz","","","Reserved for local use","Reserved for local use","ltr"],
        ["que","","qu","Runa Simi","Quechua","ltr"],
        ["raj","","","राजस्थानी","Rajasthani","ltr"],
        ["rap","","","Rapanui","Rapanui","ltr"],
        ["rar","","","Rarotongan; Cook Islands Maori","Rarotongan; Cook Islands Maori","ltr"],
        ["roa","","","Romance languages","Romance languages","ltr"],
        ["roh","","rm","Rumantsch","Romansh","ltr"],
        ["rom","","","Romany","Romany","ltr"],
        ["rum","ron","ro","Română","Romanian; Moldavian; Moldovan","ltr"],
        ["run","","rn","Kirundi","Rundi","ltr"],
        ["rup","","","Aromanian; Arumanian; Macedo-Romanian","Aromanian; Arumanian; Macedo-Romanian","ltr"],
        ["rus","","ru","Русский","Russian","ltr"],
        ["sad","","","Sandawe","Sandawe","ltr"],
        ["sag","","sg","Sängö","Sango","ltr"],
        ["sah","","","Yakut","Yakut","ltr"],
        ["sai","","","South American Indian languages","South American Indian languages","ltr"],
        ["sal","","","Salishan languages","Salishan languages","ltr"],
        ["sam","","","Samaritan Aramaic","Samaritan Aramaic","ltr"],
        ["san","","sa","संस्कृतम्","Sanskrit","ltr"],
        ["sas","","","Sasak","Sasak","ltr"],
        ["sat","","","Santali","Santali","ltr"],
        ["scn","","","Sicilianu","Sicilian","ltr"],
        ["sco","","","Scots","Scots","ltr"],
        ["sel","","","Selkup","Selkup","ltr"],
        ["sem","","","Semitic languages","Semitic languages","ltr"],
        ["sga","","","Irish, Old (to 900)","Irish, Old (to 900)","ltr"],
        ["sgn","","","Sign Languages","Sign Languages","ltr"],
        ["shn","","","Shan","Shan","ltr"],
        ["sid","","","Sidamo","Sidamo","ltr"],
        ["sin","","si","සිංහල","Sinhala; Sinhalese","ltr"],
        ["sio","","","Siouan languages","Siouan languages","ltr"],
        ["sit","","","Sino-Tibetan languages","Sino-Tibetan languages","ltr"],
        ["sla","","","Slavic languages","Slavic languages","ltr"],
        ["slo","slk","sk","Slovenčina","Slovak","ltr"],
        ["slv","","sl","Slovenščina","Slovenian","ltr"],
        ["sma","","","Southern Sami","Southern Sami","ltr"],
        ["sme","","se","Sámegiella","Northern Sami","ltr"],
        ["smi","","","Sami languages","Sami languages","ltr"],
        ["smj","","","Lule Sami","Lule Sami","ltr"],
        ["smn","","","Inari Sami","Inari Sami","ltr"],
        ["smo","","sm","Gagana Sāmoa","Samoan","ltr"],
        ["sms","","","Skolt Sami","Skolt Sami","ltr"],
        ["sna","","sn","chiShona","Shona","ltr"],
        ["snd","","sd","सिनधि","Sindhi","ltr"],
        ["snk","","","Soninke","Soninke","ltr"],
        ["sog","","","Sogdian","Sogdian","ltr"],
        ["som","","so","اللغة الصومالية","Somali","ltr"],
        ["son","","","Songhai languages","Songhai languages","ltr"],
        ["sot","","st","Sesotho","Sotho, Southern","ltr"],
        ["spa","","es","Español","Spanish; Castilian","ltr"],
        ["srd","","sc","Sardu","Sardinian","ltr"],
        ["srn","","","Sranan Tongo","Sranan Tongo","ltr"],
        ["srp","","sr","Српски","Serbian","ltr"],
        ["srr","","","Serer","Serer","ltr"],
        ["ssa","","","Nilo-Saharan languages","Nilo-Saharan languages","ltr"],
        ["ssw","","ss","SiSwati","Swati","ltr"],
        ["suk","","","Sukuma","Sukuma","ltr"],
        ["sun","","su","Basa Sunda","Sundanese","ltr"],
        ["sus","","","Susu","Susu","ltr"],
        ["sux","","","Sumerian","Sumerian","ltr"],
        ["swa","","sw","Kiswahili","Swahili","ltr"],
        ["swe","","sv","Svenska","Swedish","ltr"],
        ["syc","","","Classical Syriac","Classical Syriac","ltr"],
        ["syr","","","Syriac","Syriac","ltr"],
        ["tah","","ty","Reo Mā`ohi","Tahitian","ltr"],
        ["tai","","","Tai languages","Tai languages","ltr"],
        ["tam","","ta","தமிழ்","Tamil","ltr"],
        ["tat","","tt","Tatarça","Tatar","ltr"],
        ["tel","","te","తెలుగు","Telugu","ltr"],
        ["tem","","","Timne","Timne","ltr"],
        ["ter","","","Tereno","Tereno","ltr"],
        ["tet","","","Tetum","Tetum","ltr"],
        ["tgk","","tg","Тоҷикӣ","Tajik","ltr"],
        ["tgl","","tl","Tagalog","Tagalog","ltr"],
        ["tha","","th","ภาษาไทย","Thai","ltr"],
        ["tib","bod","bo","དབུས་སྐད་","Tibetan","ltr"],
        ["tig","","","Tigre","Tigre","ltr"],
        ["tir","","ti","ትግርኛ","Tigrinya","ltr"],
        ["tiv","","","Tiv","Tiv","ltr"],
        ["tkl","","","Tokelau","Tokelau","ltr"],
        ["tlh","","","Klingon; tlhIngan-Hol","Klingon; tlhIngan-Hol","ltr"],
        ["tli","","","Tlingit","Tlingit","ltr"],
        ["tmh","","","Tamashek","Tamashek","ltr"],
        ["tog","","","Tonga (Nyasa)","Tonga (Nyasa)","ltr"],
        ["ton","","to","Lea Faka-Tonga","Tonga (Tonga Islands)","ltr"],
        ["tpi","","","Tok Pisin","Tok Pisin","ltr"],
        ["tsi","","","Tsimshian","Tsimshian","ltr"],
        ["tsn","","tn","Setswana","Tswana","ltr"],
        ["tso","","ts","Xitsonga","Tsonga","ltr"],
        ["tuk","","tk","Туркмен / تركمن","Turkmen","ltr"],
        ["tum","","","Tumbuka","Tumbuka","ltr"],
        ["tup","","","Tupi languages","Tupi languages","ltr"],
        ["tur","","tr","Türkçe","Turkish","ltr"],
        ["tut","","","Altaic languages","Altaic languages","ltr"],
        ["tvl","","","Tuvalu","Tuvalu","ltr"],
        ["twi","","tw","Twi","Twi","ltr"],
        ["tyv","","","Tuvinian","Tuvinian","ltr"],
        ["udm","","","Udmurt","Udmurt","ltr"],
        ["uga","","","Ugaritic","Ugaritic","ltr"],
        ["uig","","ug","Uyƣurqə / ئۇيغۇرچە","Uighur; Uyghur","ltr"],
        ["ukr","","uk","Українська","Ukrainian","ltr"],
        ["umb","","","Umbundu","Umbundu","ltr"],
        ["und","","","Undetermined","Undetermined","ltr"],
        ["urd","","ur","اردو","Urdu","rtl"],
        ["uzb","","uz","Ўзбек","Uzbek","ltr"],
        ["vai","","","Vai","Vai","ltr"],
        ["ven","","ve","Tshivenḓa","Venda","ltr"],
        ["vie","","vi","Tiếng Việt","Vietnamese","ltr"],
        ["vol","","vo","Volapük","Volapük","ltr"],
        ["vot","","","Votic","Votic","ltr"],
        ["wak","","","Wakashan languages","Wakashan languages","ltr"],
        ["wal","","","Wolaitta; Wolaytta","Wolaitta; Wolaytta","ltr"],
        ["war","","","Waray","Waray","ltr"],
        ["was","","","Washo","Washo","ltr"],
        ["wel","cym","cy","Cymraeg","Welsh","ltr"],
        ["wen","","","Sorbian languages","Sorbian languages","ltr"],
        ["wln","","wa","Walon","Walloon","ltr"],
        ["wol","","wo","Wollof","Wolof","ltr"],
        ["xal","","","Kalmyk; Oirat","Kalmyk; Oirat","ltr"],
        ["xho","","xh","isiXhosa","Xhosa","ltr"],
        ["yao","","","Yao","Yao","ltr"],
        ["yap","","","Yapese","Yapese","ltr"],
        ["yid","","yi","ייִדיש","Yiddish","rtl"],
        ["yor","","yo","Yorùbá","Yoruba","ltr"],
        ["ypk","","","Yupik languages","Yupik languages","ltr"],
        ["zap","","","Zapotec","Zapotec","ltr"],
        ["zbl","","","Blissymbols; Blissymbolics; Bliss","Blissymbols; Blissymbolics; Bliss","ltr"],
        ["zen","","","Zenaga","Zenaga","ltr"],
        ["zgh","","","Standard Moroccan Tamazight","Standard Moroccan Tamazight","ltr"],
        ["zha","","za","Cuengh / Tôô / 壮语","Zhuang; Chuang","ltr"],
        ["znd","","","Zande languages","Zande languages","ltr"],
        ["zul","","zu","isiZulu","Zulu","ltr"],
        ["zun","","","Zuni","Zuni","ltr"],
        ["zxx","","","No linguistic content; Not applicable","No linguistic content; Not applicable","ltr"],
        ["zza","","","Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki","Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki","ltr"]
    ];

    function getLangObject(dataArray) {
        var langObject = {
            a3: dataArray[0],
            a3t: dataArray[1],
            a2: dataArray[2],
            name: dataArray[3],
            eng: dataArray[4],
            dir: dataArray[5]
        };

        return langObject;
    }

    function getLangMap(isAlpha2Code) {
        var i, lang, len, item, code;

        if(!alpha2Map) {
            alpha2Map = {};
            alpha3Map = {};
            for(i=0, len=data.length; i<len; i++) {
                lang = getLangObject(data[i]);
                alpha3Map[lang.a3] = lang;
                if(lang.a2) {
                    alpha2Map[lang.a2] = lang;
                }
                data[i] = lang;
            }
        }

        return isAlpha2Code ? alpha2Map : alpha3Map;
    }

    function compareLanguages(a, b, sortBy) {
        var aVal, bVal;

        sortBy = sortBy || 'a3';
        aVal = a[sortBy];
        bVal = b[sortBy];

        return aVal < bVal ? -1 : aVal > bVal ? 1 : 0;
    }


    exports.getLanguage = function (languageCode, isAlpha2Code) {
        return getLangMap(isAlpha2Code)[code];
    };

    exports.getLanguages = function (sortBy, isAlpha2Code) {
        var copy;

        sortBy = sortBy || 'a3';

        //initialize maps
        getLangMap();

        copy = data.slice();
        copy.sort(function(a,b) {
            return compareLanguages(a, b, sortBy);
        });

        return isAlpha2Code ? copy.filter(function(lang) { return !!lang.a2; }) : copy;
    };

    exports.getLabel = function (propertyName) {
        return labels[propertyName];
    };

    exports.isValid = function (languageCode, isAlpha2Code) {
        return !! getLangMap(isAlpha2Code)[code];
    };

    exports.isRtl = function (languageCode, isAlpha2Code) {
        var language = getLangMap(isAlpha2Code)[code] || {};

        return language.dir == 'rtl';
    };

//allow executing by nodejs in the server or by javascript in the browser
})(typeof exports === 'undefined'? this['languages']={}: exports);
